добавлены
Filosuf/ImageFeed pull request #1
Opened 2022-11-02 20:29 UTC by Filosuf

- экран профиля
- детальный экран изображения

2022-11-03 09:23 UTC, ABashkirova requested changes
Привет, Евгений! 

Отличная работа, давайте закончим работу выполнив все пункты чекиста + небольшое замечание по порядку вызова функций в настройке scroll view. 

Также, рекомендую больше уделять внимания аккуратности работы. Это один из важных пунктов, так как работодатель в тестовых заданиях(и портфолио) зачастую обращает больше внимания оформлению работы, нежели самому решению задачи.

2022-11-03 09:25 UTC, ABashkirova commented
Еще спорный отступ у кнопки выхода. 
Судя по фигме, должна быть центровка относительно аватара. Либо же 55 сверху. У вас 56.
<img width="439" alt="Screenshot 2022-11-03 at 13 11 15" src="https://user-images.githubusercontent.com/20269264/199685870-782a3b6b-353c-4820-8ef0-d58cd45e5101.png">

2022-11-03 09:29 UTC, ABashkirova commented
<img width="391" alt="Screenshot 2022-11-03 at 13 25 37" src="https://user-images.githubusercontent.com/20269264/199686113-57d0775f-3101-4d10-9338-6eef84442d75.png">
Обычно принято выгрузить либо пак в x3, либо выставлять параметр single scale для векторных изображений в x1.

Вот так фигме можно выгрузить весь пак в трех размерах.

<img width="1800" alt="Screenshot 2022-11-03 at 13 26 35" src="https://user-images.githubusercontent.com/20269264/199686359-8c472101-59ad-4a56-8431-da53b96a76a1.png">

При выгрузке обратите внимание, что выгружается не внутренний элемент, а компонент иконки (пиктограмма с ромбиком) – и сбоку три размера.  Сейчас у вас выгружено одно изображение, не иконка, и она может пикселиться на устройстве.

2022-11-03 20:22 UTC, Filosuf commented
Александра, спасибо за комментарии. Раньше IBAction вместе с IBOutlet размещал. Иконки тоже не знал как сразу три выгрузить. У меня вопрос: Как в Assets узнать что уже добавлено в 1х (векторное изображение и растр) и нужно ли добавлять 2х 3х?

2022-11-04 07:52 UTC, ABashkirova commented
> Раньше IBAction вместе с IBOutlet размещал. Иконки тоже не знал как сразу три выгрузить.

Это OK, не все сразу :)

 > Как в Assets узнать что уже добавлено в 1х (векторное изображение и растр) и нужно ли добавлять 2х 3х?

Выделяете изображение, в инспекторе - Single Scale поставить.

<img width="985" alt="Screenshot 2022-11-04 at 11 50 11" src="https://user-images.githubusercontent.com/20269264/199920716-e074ec60-94a2-4500-afa4-dba9012662ea.png">

2022-11-04 07:55 UTC, ABashkirova approved these changes
Отличная работа!

2022-11-04 07:55 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
>      }
Сгенерированные и не используемые методы можно смело удалять, если понадобится - не потеряетесь и допишите)

2022-11-17 08:25 UTC, merged