Sprint 10
Filosuf/ImageFeed pull request #2
Opened 2022-11-14 13:50 UTC by Filosuf

2022-11-14 19:09 UTC, mmbabaev commented on ImageFeed/Auth/AuthViewController.swift
> +                    let responseBody = try JSONDecoder().decode(OAuthTokenResponseBody.self, from: data)
то есть создать один раз JSONDecoder

2022-11-14 19:24 UTC, mmbabaev commented on ImageFeed/Service/OAuth2/OAuth2Service.swift
> +                completion(.failure(error!))
разверните ошибку в `if` или используйте свою Networkerror

2022-11-14 19:24 UTC, mmbabaev commented on ImageFeed/Service/OAuth2/OAuth2Service.swift
> +                //completion(.failure(NetworkError.codeError))
удаляйте закомментированный код перед отправкой на ревью

2022-11-15 11:06 UTC, Filosuf commented
Насчёт JSONDecoder не совсем понял. Вроде бы у меня тоже создаётся только один раз, для этого добавлять строку и переменную не вижу смысла, читаемость тоже не улучшает.

2022-11-15 21:58 UTC, mmbabaev requested changes

2022-11-15 21:58 UTC, mmbabaev commented on ImageFeed/Service/OAuth2/OAuth2Service.swift
> +    private func decoding(data: Data, completion: @escaping (Result<String, Error>) -> Void) {
для чего тут сделан completion, а не возвращаемое значение?

2022-11-15 21:58 UTC, mmbabaev commented on ImageFeed/Service/OAuth2/OAuth2Service.swift
> +                    completion(.failure(error))
При failure декодинга completion будет вызван два раза. Один раз здесь

2022-11-15 21:58 UTC, mmbabaev commented on ImageFeed/Service/OAuth2/OAuth2Service.swift
> +                completion(.success(resultToken))
второй раз здесь success при фейле

2022-11-17 08:25 UTC, merged