Sprint 11
Filosuf/ImageFeed pull request #3
Opened 2022-11-29 17:12 UTC by Filosuf

2022-11-30 11:31 UTC, ABashkirova requested changes
Обязательно нужно найти все места, где происходит вызов UI блоков внутри фетчей – Xcode сыплет ошибками

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Service/OAuth2/OAuth2Service.swift
> +
Имхо, я бы разделила задачи: проверять на состоянии гонки отдельно, от отправки запроса. 
Сейчас это место выглядит перегруженным

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Service/OAuth2/OAuth2TokenStorage.swift
Можно удалять userDefaults отсюда, а еще лучше заменить на KeychainWrapper.standard и обращаться через свойство

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Service/OAuth2/OAuth2TokenStorage.swift
> +            print("Save token \(newValue ?? "Token empty")")
выглядит очень нагруженно и "отладночно", если здесь ошибки не произойдет, так можно убрать это все?

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Service/Profile/ProfileImageService.swift
> +    private (set) var avatarURL: String?
Обычно принято вот такое написание
```suggestion
    private(set) var avatarURL: String?
```

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Splash/SplashViewController.swift
> +            UIBlockingProgressHUD.show()
я бы этот вызов спрятала в getProfile, иначе чаще всего ошибаешься при масштабировании кода и забываешь крутить индикатор

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Splash/SplashViewController.swift
> +    }
если не понадобился - стоит удалять

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Splash/SplashViewController.swift
>          startAplication()
опечатки бы тоже править, [spellChecking](https://sarunw.com/posts/spell-checking-in-xcode/) выручает

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Splash/SplashViewController.swift
> +                print("Error = \(error.localizedDescription)")
мне не очень нравятся отладочные спринты в работе, будет здорово, если перед сдачей будете такое удалять

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Splash/SplashViewController.swift
> +                self.alertPresenter.showErrorAlert(message: "Не удалось войти в систему", action: {})
```suggestion
                self.alertPresenter.showErrorAlert(message: "Не удалось войти в систему", action: { })
```

2022-11-30 11:31 UTC, ABashkirova commented on ImageFeed/Splash/SplashViewController.swift
> +            }
Вызов обновления UI не на главной очереди

2022-12-01 05:35 UTC, ABashkirova commented on ImageFeed/Splash/SplashViewController.swift
> +            }
Приношу извинения, тут неактуальный комментарий

2022-12-01 05:37 UTC, ABashkirova commented
@Filosuf Приношу извинения, отправила работу на доработку без оснований

Если перепрешлете – сразу отправлю апрув

2022-12-01 08:11 UTC, Filosuf commented on ImageFeed/Service/OAuth2/OAuth2Service.swift
> +        assert(Thread.isMainThread)
Да, это из авторского решения

2022-12-01 08:36 UTC, Filosuf commented on ImageFeed/Splash/SplashViewController.swift
> +            UIBlockingProgressHUD.show()
Может быть, пока выглядит для меня некрасиво, когда добавляется один и тот же элемент 2 раза. Если добавить появление индикатора в getProfile, то при первом запуске UIBlockingProgressHUD.show() будет вызвана 2 раза до того как скроется. О масштабируемости не думал. В таком случае может быть стоит добавить проверку в UIBlockingProgressHUD.show() не крутится ли сейчас индикатор, и если да, то ничего не делать при вызове. Так правильно?

2022-12-01 08:39 UTC, Filosuf commented on ImageFeed/Splash/SplashViewController.swift
>          startAplication()
Супер, каждый раз какая-то очень полезная информация по SDK. Включил, спасибо.

2022-12-01 08:41 UTC, Filosuf commented
Спасибо за внимание к коду и стилистике. Мне это очень нужно. С ошибками вроде бы разобрались.

2022-12-01 17:27 UTC, ABashkirova commented on ImageFeed/Splash/SplashViewController.swift
> +            UIBlockingProgressHUD.show()
>  UIBlockingProgressHUD.show() не крутится ли сейчас индикатор и если да, то ничего не делать при вызове

👍🏻

2022-12-01 17:29 UTC, ABashkirova commented on ImageFeed/Splash/SplashViewController.swift
> +            case .failure(_):
```suggestion
            case .failure:
```

2022-12-01 17:29 UTC, ABashkirova approved these changes
✅

2022-12-02 11:56 UTC, merged